import { AircraftType } from "./apiModels";

export const anyAircraftType = (overwrites?: Partial<AircraftType>): Required<AircraftType> => ({
    id: "1",
    validFrom: "2024-01-01T00:00:00.000Z",
    minimumTemperature: 1,
    maximumTemperature: 2,
    windSpeed: 1,
    relativeHumidity: 1,
    rain: 1,
    visibility: 1,
    cloudCeilingHeight: 1,
    airDensity: 1,
    name: "Aircraft Type",
    productLine: "pl",
    createTime: "2024-01-01T00:00:00.000Z",
    updateTime: "2024-01-01T00:00:00.000Z",
    performanceDataFileUrl: "",
    performanceDataFileVersion: 1,
    version: 1,
    validTo: "2025-01-01T00:00:00.000Z",
    wakeTurbulenceCategory: "",
    maximumAirspeed: 1,
    maximumTranslationalAcceleration: 1,
    maximumLoadFactor: 1,
    maximumYawRateInHover: 1,
    maximumYawAccelerationInHover: 1,
    maximumTurnRateInCoordinatedFlight: 1,
    maximumTurnAccelerationInCoordinatedFlight: 1,
    serviceCeiling: 1,
    climbRate: 1,
    climbAcceleration: 1,
    descendRate: 1,
    descendAcceleration: 1,
    massAndBalanceData: {
        cgPosition: {
            x: 1,
            y: 1,
        },
        bem: 1,
        mtom: 1,
        longCgEnvelopePoints: [],
        latCgEnvelopePoints: [],
    },
    aircraftResources: [],
    pilotSeats: 1,
    passengerSeats: 1,
    batterySlots: 1,
    luggageCompartments: 1,
    otherResources: 1,
    createdBy: "",
    updatedBy: "",
    aircraftCount: 1,
    ...overwrites,
});
