import { Route } from "./models";

export const anyRoute = (overwrites?: Partial<Route>): Route => ({
    id: 42,
    routeOptionId: 34,
    description: "any route description",
    name: "route40",
    createdAt: "2022-03-28T13:06:14.158813Z",
    plannedBy: "some person",
    distance: 42,
    duration: 42,
    remainingEnergy: 42,
    refAltAmsl: 0,
    waypoints: [
        {
            id: 59,
            name: "Roma Termini",
            lat: 41.899,
            lng: 12.504,
            alt: 0,
            altAboveRefAlt: 0,
            rnp: 0.2,
            transitionType: "fly-by",
            transitionRadius: 100,
            speed: 20.577,
            heading: 239,
            routeSequenceIndex: 0,
            targetTimeOver: 0,
        },
        {
            id: 58,
            name: "Leonardo da Vinci",
            lat: 41.82,
            lng: 12.274,
            alt: 0,
            altAboveRefAlt: 0,
            rnp: 0.2,
            transitionType: "fly-by",
            transitionRadius: 100,
            speed: 20.577,
            heading: 264,
            routeSequenceIndex: 5,
            targetTimeOver: 1225.761,
        },
    ],
    ...overwrites,
});
