nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.1.1.cjs

npmScopes:
    volocopter:
        npmRegistryServer: https://pkgs.dev.azure.com/volocopter/_packaging/common/npm/registry/
        npmAlwaysAuth: true
    voloiq-typescript-api:
        npmRegistryServer: https://pkgs.dev.azure.com/volocopter/voloiq/_packaging/voloiq-typescript-api/npm/registry/
        npmAlwaysAuth: true
