import type { PlanSummary } from "./apiModels";

export const anyPlanSummary = (overwrites?: Partial<PlanSummary>): Required<PlanSummary> => ({
    id: "1",
    commercialPlanId: "1",
    commercialPlanStatus: "DRAFT",
    commercialScheduleItemId: "1",
    commercialScheduleItemStatus: "DRAFT",
    flightNumber: "1111",
    departureVertiportCode: "D01",
    arrivalVertiportCode: "A01",
    departureTime: "2024-01-01T15:00:00.000Z",
    arrivalTime: "2024-01-01T16:00:00.000Z",
    aircraftTypeName: "aircraft",
    prices: [{ price: 5, currency: "EUR" }],
    offers: [{ offerRunwayValue: 1, offerRunwayUnit: "HOURS" }],
    scheduleItemConnectionStatus: "CONSISTENT",
    isCustomized: true,
    isNoCustomOffer: false,
    isCustomOverwritten: false,
    customCommercialScheduleItemId: "1",
    customItemStatus: "DRAFT",
    customPrice: 10,
    customOfferRunwayUnit: "HOURS",
    customOfferRunwayValue: 2,
    customComments: "comments",
    isDeleted: false,
    isCustomScheduleItemDeletionReq: false,
    ...overwrites,
});
