import { Route } from "./apiModels";

export const anyRoute = (overwrites?: Partial<Route>): Required<Route> => ({
    id: 1,
    name: "Route",
    description: "",
    plannedBy: "Flight-Planning User",
    createdAt: "0004-01-01T00:00:000Z",
    distance: 1,
    duration: 1,
    refAltAmsl: 0,
    remainingEnergy: 1,
    validationStatus: "valid",
    validityDate: "0005-01-01",
    routeOptionId: 1,
    waypoints: [
        {
            id: 1,
            name: "waypoint",
            lat: 1,
            lng: 1,
            alt: 0,
            altAboveRefAlt: 0,
            rnp: 0,
            transitionType: "",
            transitionRadius: 1,
            sarsId: "",
            speed: 1,
            heading: 1,
            routeSequenceIndex: 0,
            targetTimeOver: 0,
            routeSegment: "",
            isVertiport: true,
        },
    ],
    alerts: [],
    routeEnergySettings: {
        windSpeed: 0,
        windDirection: 0,
        takeoffMass: 0,
        batteryCycles: 0,
        airDensity: 0,
        ambientTemperature: 0,
        transitionAltitude: 0,
        airspeedCsfl: 0,
        descendAngleCsfl: 0,
        climbTakeoff: 0,
        climbTouchDown: 0,
        maxClimbRate: 0,
        maxDescendRate: 0,
        loiterAltitude: 0,
        loiterTime: 0,
        loiterTimeCsfl: 0,
        batteryCapacityOrig: 44.6,
        finalReserve: 0,
        unusableEnergy: 0,
        discretionaryEnergy: 0,
        additionalEnergy: 0,
        extraEnergy: 0,
        contingencyEnergy: 0,
        goAroundEnergy: 0,
        integrationTimeStepsSeconds: 0,
        departureTaxiDistance: 0,
        departureTaxiSpeed: 0,
        arrivalTaxiDistance: 0,
        arrivalTaxiSpeed: 0,
        csflEnergyOverhead: 0,
        pdmTwoEfficiencyLoss: 0,
        maxTimeToCsfl: 0,
        cruiseAltitude: 0,
        pathGradient: 0,
        csflCoverageRadius: 0,
        temperatureMinLimit: 0,
        temperatureMaxLimit: 0,
        windSpeedMinLimit: 0,
        windSpeedMaxLimit: 0,
        visibiltyMinLimit: 0,
        cloudCeilingMinLimit: 0,
        precipitationMaxLimit: 0,
        relativeHumidityMaxLimit: 0,
        horizontalObstacleClearance: 0,
        verticalObstacleClearance: 0,
    },
    isAltitudeProfileGenerated: false,
    ...overwrites,
});
