import { v4 as uuidV4 } from "uuid";
import { anyTipTapJson } from "../../common";
import type { FlightTestOrder } from "./apiModels";

const someDate = new Date("2024-04-01T00:00:00Z");

export const anyFlightTestOrder = (overwrites: Partial<FlightTestOrder> = {}): FlightTestOrder => ({
    id: uuidV4(),
    ftoId: "FTO-V21-2023-002",
    missionTitle: "Flt#53: Aerocover Validation & ADAHRS Phase 3.1",
    masterModel: "VC2-1",
    msn: "MSN 01",
    createTime: someDate.toISOString(),
    missionScenarios: JSON.stringify(anyTipTapJson("short summary")),
    missionObjective: JSON.stringify(anyTipTapJson("short summary")),
    flightTestPlanIds: [],
    riskLevel: "HIGH",
    flightTestCategory: "Cat. 1",
    aircraftCallsign: "Foo",
    responsibleOperator: "Foo",
    model: "Foo",
    flightConditions: "Foo",
    revision: "Foo",
    issueDateForFlightConditions: someDate.toISOString(),
    permitToFly: "Foo",
    issueDateForPermit: someDate.toISOString(),
    expiredDateForPermit: someDate.toISOString(),
    pilotInCommand: "First Name",
    category: "2",
    testConductor: "Second Name",
    secondPilot: "Third Name",
    firstObserver: "N/A",
    secondObserver: "N/A",
    flyingMass: 2,
    plannedDuration: "20",
    charge: 2,
    minCellVolt: 2,
    flyingLong: 2,
    flyingLat: 2,
    longRange: "0.3",
    latRange: "0.4",
    notesToAircraft: "These are notes",
    maxTestSpeed: 3,
    maxTestAlt: 3,
    vne: 3,
    maxRoll: 3,
    maxPitch: 3,
    weatherLimits: "no limits",
    weatherObserved: "great",
    createdBy: "Fourth Name",
    ...overwrites,
});
