import { RouteTemplate } from "../models";

export const anyRouteTemplate = (overrides?: Partial<RouteTemplate>): RouteTemplate => ({
    id: 44,
    name: "Demo",
    description: "",
    plannedBy: "voloiq-flightplanning",
    createdAt: "2023-11-27T10:26:19.236Z",
    distance: 0.1,
    duration: 0.1,
    refAltAmsl: 0.1,
    remainingEnergy: 0.1,
    validationStatus: "not_yet_validated",
    validityDate: "2023-11-27T10:26:19.236Z",
    alerts: [],
    routeEnergySettings: {
        windSpeed: 0.1,
        windDirection: 180.1,
        takeoffMass: 950,
        batteryCycles: 100,
        airDensity: 1.15,
        ambientTemperature: 20.1,
        transitionAltitude: 30,
        airspeedCsfl: 38,
        descendAngleCsfl: 6,
        climbTakeoff: 2.1,
        climbTouchDown: -2.1,
        maxClimbRate: 3.0988,
        maxDescendRate: 2.54,
        loiterAltitude: 3,
        loiterTime: 10,
        loiterTimeCsfl: 10,
        batteryCapacityOrig: 48.1,
        finalReserve: 2.5,
        unusableEnergy: 3.5,
        discretionaryEnergy: 0.1,
        additionalEnergy: 0.1,
        extraEnergy: 0.1,
        contingencyEnergy: 10,
        integrationTimeStepsSeconds: 30,
        departureTaxiDistance: 50.1,
        departureTaxiSpeed: 15.1,
        arrivalTaxiDistance: 50.1,
        arrivalTaxiSpeed: 15.1,
        csflEnergyOverhead: 10.1,
        pdmTwoEfficiencyLoss: 13.1,
        maxTimeToCsfl: 6.1,
    },
    ...overrides,
});
