import { Vertiport } from "./apiModels";

export const anyVertiport = (overwrites?: Partial<Vertiport>): Required<Vertiport> => ({
    id: "1",
    validFrom: "2024-01-01T00:00:000Z",
    minimumTemperature: 2,
    maximumTemperature: 3,
    windSpeed: 2,
    relativeHumidity: 2,
    rain: 2,
    visibility: 4,
    cloudCeilingHeight: 4,
    airDensity: 2,
    name: "Vertiport",
    productLine: "VOLOCITY",
    createTime: "2024-01-01T00:00:000Z",
    updateTime: "2024-01-01T00:00:000Z",
    performanceDataFileUrl: "",
    performanceDataFileVersion: 0,
    version: 2,
    validTo: "2025-01-01T00:00:000Z",
    wakeTurbulenceCategory: "",
    maximumAirspeed: "",
    maximumTranslationalAcceleration: "",
    maximumLoadFactor: "",
    maximumYawRateInHover: "",
    maximumYawAccelerationInHover: "",
    maximumTurnRateInCoordinatedFlight: "",
    maximumTurnAccelerationInCoordinatedFlight: "",
    serviceCeiling: "",
    climbRate: "",
    climbAcceleration: "",
    descendRate: "",
    descendAcceleration: "",
    massAndBalanceData: {
        cgPosition: {
            x: 2,
            y: 2,
        },
        bem: 2,
        mtom: 2,
        longCgEnvelopePoints: [],
        latCgEnvelopePoints: [],
    },
    aircraftResources: [],
    pilotSeats: 0,
    passengerSeats: 0,
    batterySlots: 0,
    luggageCompartments: 0,
    otherResources: 0,
    createdBy: "user@volocopter.com",
    updatedBy: "KafkaTask",
    aircraftCount: 2,
    performanceModel: "UNKNOWN",
    maxDurationToCsfl: "",
    code: "code",
    shortName: "vp",
    ...overwrites,
});
