import {
    AircraftTechnicalStatus,
    MissionBoardingStatus,
    MissionConflict,
    MissionCreateSource,
    ReservationStatus,
    Service,
    StatusOfMission,
    TypeOfOperation,
} from "@voloiq-typescript-api/network-scheduling-types";
import { Mission } from "@voloiq/network-schedule-management-api/v1";

const someDate = new Date("2024-04-01T00:00:00Z");

export const anyMission = (overwrites?: Partial<Mission>) => {
    const mission: Mission = {
        id: "d9381aa2-0955-47a2-ada8-5dcd49117d7d",
        flightNumber: "VC123",
        departureVertiportId: "ce118b6e-d8e1-11e7-9296-cec278b6b50a",
        missionBoardingStatus: MissionBoardingStatus.BOARDING_OPEN,
        departureVertiportCode: "XRJ",
        departureDateTime: "2023-04-11T19:00:00Z",
        arrivalVertiportId: "f5cf2755-0eb0-484a-bef6-67f0f604e8d5",
        arrivalVertiportCode: "FCO",
        assignments: {
            id: "d9381aa2-0955-47a2-ada8-5dcd49117d7d",
            aircraftId: "647101a1-3b79-452a-868b-2d15073285a6",
            pilotId: "3679f481-1517-4df6-a8e9-debe126fb5a0",
            createTime: "2023-04-06T09:42:29.991Z",
            updateTime: "2023-04-12T08:15:13.438Z",
            aircraftMSN: "1112",
            aircraftRegistration: "TEST",
            aircraftTypeName: "TEST",
            batteryId: "291627c0-27e8-4361-b5d4-4d7e79238a46",
            batteryName: "todo",
            aircraftReservationStatus: ReservationStatus.UNKNOWN,
            aircraftTechnicalStatus: AircraftTechnicalStatus.SERVICEABLE,
            pilotReservationStatus: ReservationStatus.ACCEPTED,
            pilotFirstName: "Simon",
            pilotMiddleName: "L",
            pilotSurName: "Bayer",
        },
        arrivalDateTime: "2022-04-11T19:15:00Z",
        estimatedArrivalDateTime: someDate.toISOString(),
        estimatedDepartureDateTime: someDate.toISOString(),
        service: Service.TEST,
        messages: [
            {
                id: "36eb3ee3-0c8d-4cb9-a45d-a340a872add5",
                message: "test message",
                authorEmail: "amina.asif_ext@volocopter.com",
                publishDate: "2023-06-19T10:12:26.704Z",
                messageCategory: "AIRCRAFT",
                userRole: "OCC",
            },
        ],
        typeOfOperation: TypeOfOperation.PILOTED,
        statusOfMission: StatusOfMission.PLANNED,
        actualDepartureDateTime: "2023-04-11T19:00:00Z",
        createTime: "2023-04-11T19:00:00Z",
        updateTime: "2023-04-11T19:00:00Z",
        actualArrivalDateTime: "2023-04-11T19:15:00Z",
        bookings: [],
        missionConflicts: [MissionConflict.PILOT_WITHOUT_PILOT_SEAT_ASSIGNMENT],
        missionAssignmentConfirmed: true,
        aircraftReservationStartDateTime: "2023-05-04T08:00:00Z",
        aircraftReservationEndDateTime: "2023-05-04T09:00:00Z",
        crewReservationStartDateTime: "2023-05-04T08:00:00Z",
        crewReservationEndDateTime: "2023-05-04T09:00:00Z",
        clearance: true,
        isClosable: true,
        createdOperationalFlightPlans: 10,
        synchronizedWithLeon: false,
        source: MissionCreateSource.NETWORK_SCHEDULE,
        subProcess: {
            resourceAssignmentDone: false,
            batteryAssignmentDone: false,
            pilotAcceptanceDone: false,
            operationalFlightPlanDone: false,
            groundOpsReadyDone: false,
            utmClearanceDone: false,
            actualDepartureTimeDone: false,
            actualArrivalTimeDone: false,
            groundOpsCompletionDone: false,
            flightClosedDone: false,
            telemetryDataUploadDone: false,
            createTime: "2023-09-01T11:49:31.757Z",
            updateTime: "2023-09-01T11:49:32.852Z",
            id: "8d37fe39-32ae-4fb2-858d-b0b87671a526",
            pilotDiaryDone: false,
            airlineAcceptanceDone: false,
            paxCheckedInDone: false,
            pilotBriefingAcceptanceDone: false,
        },
        checkLists: [
            {
                name: "AIRCRAFT",
                severity: "ERROR",
                checkListItems: [],
            },
            {
                name: "BATTERY",
                severity: "UNKNOWN",
                checkListItems: [],
            },
            {
                name: "CREW",
                severity: "ERROR",
                checkListItems: [],
            },
            {
                name: "FLIGHT_PLAN",
                severity: "UNKNOWN",
                checkListItems: [],
            },
            {
                name: "GENERAL",
                severity: "UNKNOWN",
                checkListItems: [],
            },
            {
                name: "GROUND_OPERATION",
                severity: "UNKNOWN",
                checkListItems: [],
            },
            {
                name: "PASSENGER",
                severity: "UNKNOWN",
                checkListItems: [],
            },
            {
                name: "NOTAMS",
                severity: "UNKNOWN",
                checkListItems: [],
            },
            {
                name: "WEATHER",
                severity: "UNKNOWN",
                checkListItems: [],
            },
        ],
        version: 1,
        weatherLastUpdated: someDate.toISOString(),
        delayCodes: [],
        ...overwrites,
    };
    return mission;
};
