export const METERS_TO_FEET = 3.280_84;
export const FEET_TO_METERS = 1 / METERS_TO_FEET;
export const METERSPERSEC_TO_FEETPERMIN = 196.85;
export const FEETPERMIN_TO_METERSPERSEC = 1 / METERSPERSEC_TO_FEETPERMIN;
export const NAUTICAL_MILES_TO_METERS = 1852;
export const METERS_TO_NAUTICAL_MILES = 1 / NAUTICAL_MILES_TO_METERS;
export const KNOTS_TO_METERS_PER_SECOND = 0.514_444;
export const METERS_PER_SECOND_TO_KNOTS = 1 / KNOTS_TO_METERS_PER_SECOND;
